import jsPDF from "jspdf";
import "jspdf-autotable";

const reportSections = [
  {
    title: "1. General Points",
    entries: [
      "Academic calendar update — Mid-semester exams rescheduled to Week 16.",
      "Lab maintenance — CS Lab 3 will be unavailable March 30-31.",
    ],
  },
  {
    title: "2. Faculty Joined / Relieved",
    entries: ["Dr. Ananya Gupta joined as Assistant Professor (CSE) on 25-Mar-2026."],
  },
  {
    title: "3. Faculty Achievements",
    entries: [
      "Dr. Priya Mehta — Best Paper Award at IEEE Conference (25-Mar-2026).",
      "Prof. Raj Patel — Invited Keynote at National Symposium (28-Mar-2026).",
    ],
  },
  { title: "4. Student Achievements", entries: ["Arun Verma — 1st place at HackIndia 2026, National Level."] },
  { title: "5. Department Achievements", entries: ["NAAC A++ Accreditation confirmed for 2026-2031."] },
  { title: "6. Faculty Events", entries: ["No entries this week."] },
  { title: "7. Student Events", entries: ["Tech Symposium 2026 — 150 participants, organized by Dr. Sharma."] },
  { title: "8. Non-Technical Events", entries: ["No entries this week."] },
  { title: "9. Industry Visits", entries: ["Visit to TCS Innovation Labs, Pune — 45 students, 28-Mar-2026."] },
  { title: "10. Hackathons", entries: ["No entries this week."] },
  { title: "11. Faculty Certifications", entries: ["Prof. Kumar — AWS Solutions Architect (27-Mar-2026)."] },
  { title: "12. Faculty Visits", entries: ["Dr. Mehta visited IIT Bombay for research collaboration."] },
  { title: "13. Patents", entries: ["No entries this week."] },
  { title: "14. VEDIC Programs", entries: ["Yoga and wellness session conducted for staff — 20 participants."] },
  {
    title: "15. Placements",
    entries: [
      "Arun Verma — Google, 24 LPA, SDE-1.",
      "Sneha Rao — Microsoft, 22 LPA, Software Engineer.",
      "Karthik Nair — Amazon, 18 LPA, SDE Intern.",
    ],
  },
  { title: "16. MoUs", entries: ["No entries this week."] },
  { title: "17. Skill Development Programs", entries: ["Python Bootcamp — 3 days, 80 participants, by Prof. Singh."] },
];

export function downloadReportPDF() {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Header background
  doc.setFillColor(79, 70, 229); // primary indigo
  doc.rect(0, 0, pageWidth, 45, "F");

  // Header text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Department of Computer Science & Engineering", pageWidth / 2, 18, { align: "center" });

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Weekly Report — Week 14, March 2026", pageWidth / 2, 28, { align: "center" });

  doc.setFontSize(9);
  doc.text("Prepared on: March 31, 2026 | Submitted by: HOD Office", pageWidth / 2, 37, { align: "center" });

  y = 55;
  doc.setTextColor(0, 0, 0);

  for (const section of reportSections) {
    // Check if we need a new page
    const estimatedHeight = 12 + section.entries.length * 8;
    if (y + estimatedHeight > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }

    // Section title
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229);
    doc.text(section.title, margin, y);
    y += 2;

    // Underline
    doc.setDrawColor(200, 200, 220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;

    // Entries
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);

    for (const entry of section.entries) {
      const lines = doc.splitTextToSize(`•  ${entry}`, pageWidth - margin * 2 - 5);
      if (y + lines.length * 6 > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        y = 20;
      }
      doc.text(lines, margin + 3, y);
      y += lines.length * 6;
    }

    y += 6;
  }

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text(
    "This report was auto-generated by WeeklySync. All data verified by respective coordinators.",
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: "center" }
  );

  doc.save("WeeklyReport_Week14_March2026.pdf");
}
