import AppLayout from "@/components/AppLayout";
import { Button } from "@/components/ui/button";
import { FileText, Download, Printer } from "lucide-react";
import { downloadReportPDF } from "@/lib/generateReport";

const reportSections = [
  {
    title: "1. General Points",
    entries: [
      "Academic calendar update — Mid-semester exams rescheduled to Week 16.",
      "Lab maintenance — CS Lab 3 will be unavailable March 30-31.",
    ],
  },
  {
    title: "2. Faculty Joined / Relieved",
    entries: ["Dr. Ananya Gupta joined as Assistant Professor (CSE) on 25-Mar-2026."],
  },
  {
    title: "3. Faculty Achievements",
    entries: [
      "Dr. Priya Mehta — Best Paper Award at IEEE Conference (25-Mar-2026).",
      "Prof. Raj Patel — Invited Keynote at National Symposium (28-Mar-2026).",
    ],
  },
  { title: "4. Student Achievements", entries: ["Arun Verma — 1st place at HackIndia 2026, National Level."] },
  { title: "5. Department Achievements", entries: ["NAAC A++ Accreditation confirmed for 2026-2031."] },
  { title: "6. Faculty Events", entries: ["No entries this week."] },
  { title: "7. Student Events", entries: ["Tech Symposium 2026 — 150 participants, organized by Dr. Sharma."] },
  { title: "8. Non-Technical Events", entries: ["No entries this week."] },
  { title: "9. Industry Visits", entries: ["Visit to TCS Innovation Labs, Pune — 45 students, 28-Mar-2026."] },
  { title: "10. Hackathons", entries: ["No entries this week."] },
  { title: "11. Faculty Certifications", entries: ["Prof. Kumar — AWS Solutions Architect (27-Mar-2026)."] },
  { title: "12. Faculty Visits", entries: ["Dr. Mehta visited IIT Bombay for research collaboration."] },
  { title: "13. Patents", entries: ["No entries this week."] },
  { title: "14. VEDIC Programs", entries: ["Yoga and wellness session conducted for staff — 20 participants."] },
  {
    title: "15. Placements",
    entries: [
      "Arun Verma — Google, 24 LPA, SDE-1.",
      "Sneha Rao — Microsoft, 22 LPA, Software Engineer.",
      "Karthik Nair — Amazon, 18 LPA, SDE Intern.",
    ],
  },
  { title: "16. MoUs", entries: ["No entries this week."] },
  { title: "17. Skill Development Programs", entries: ["Python Bootcamp — 3 days, 80 participants, by Prof. Singh."] },
];

export default function ReportPreviewPage() {
  return (
    <AppLayout>
      <div className="animate-fade-in space-y-6">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="font-display text-2xl font-bold text-foreground">Report Preview</h1>
            <p className="text-sm text-muted-foreground mt-1">
              Review the final formatted report before submission.
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Button variant="outline" size="sm" className="gap-1.5">
              <Printer className="w-3.5 h-3.5" />
              Print
            </Button>
            <Button variant="hero" size="sm" className="gap-1.5">
              <Download className="w-3.5 h-3.5" />
              Export PDF
            </Button>
          </div>
        </div>

        {/* Report Document */}
        <div className="bg-card rounded-xl shadow-elevated max-w-4xl mx-auto">
          {/* Header */}
          <div className="gradient-primary rounded-t-xl p-8 text-center">
            <h2 className="font-display text-xl font-bold text-primary-foreground">
              Department of Computer Science & Engineering
            </h2>
            <p className="text-primary-foreground/80 text-sm mt-1">
              Weekly Report — Week 14, March 2026
            </p>
            <p className="text-primary-foreground/60 text-xs mt-2">
              Prepared on: March 31, 2026 | Submitted by: HOD Office
            </p>
          </div>

          {/* Content */}
          <div className="p-8 space-y-6">
            {reportSections.map((section) => (
              <div key={section.title}>
                <h3 className="font-display font-semibold text-foreground text-sm border-b border-border pb-2 mb-3">
                  {section.title}
                </h3>
                <ul className="space-y-1.5">
                  {section.entries.map((entry, i) => (
                    <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 shrink-0" />
                      {entry}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div className="border-t border-border p-6 text-center">
            <p className="text-xs text-muted-foreground">
              This report was auto-generated by WeeklySync. All data verified by respective coordinators.
            </p>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
